// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBceW5bSe9Z4ne8ZwSyuCREAavrKqq08Ew',
    appId: '1:814682837268:web:6a6af5d29740d15ac1b201',
    messagingSenderId: '814682837268',
    projectId: 'movie-streaming-app-ca279',
    authDomain: 'movie-streaming-app-ca279.firebaseapp.com',
    storageBucket: 'movie-streaming-app-ca279.firebasestorage.app',
    measurementId: 'G-C4CY0KYMES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv6gtSfkexkMpADD3qw94rCwtYdXcIPkE',
    appId: '1:814682837268:android:f52421f885e38d11c1b201',
    messagingSenderId: '814682837268',
    projectId: 'movie-streaming-app-ca279',
    storageBucket: 'movie-streaming-app-ca279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC75ODC6NkjxIRiOIaoAeMieawjaw5nHu8',
    appId: '1:814682837268:ios:922b96e9b1f26793c1b201',
    messagingSenderId: '814682837268',
    projectId: 'movie-streaming-app-ca279',
    storageBucket: 'movie-streaming-app-ca279.firebasestorage.app',
    iosBundleId: 'com.example.movieStreamingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC75ODC6NkjxIRiOIaoAeMieawjaw5nHu8',
    appId: '1:814682837268:ios:922b96e9b1f26793c1b201',
    messagingSenderId: '814682837268',
    projectId: 'movie-streaming-app-ca279',
    storageBucket: 'movie-streaming-app-ca279.firebasestorage.app',
    iosBundleId: 'com.example.movieStreamingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBceW5bSe9Z4ne8ZwSyuCREAavrKqq08Ew',
    appId: '1:814682837268:web:ca874c9ecab205a5c1b201',
    messagingSenderId: '814682837268',
    projectId: 'movie-streaming-app-ca279',
    authDomain: 'movie-streaming-app-ca279.firebaseapp.com',
    storageBucket: 'movie-streaming-app-ca279.firebasestorage.app',
    measurementId: 'G-DRJFJXZP8W',
  );
}
